"""
Constants for goldfish models.
"""

# See our paper for details on language codes.
langs_5mb = ['ang_latn', 'apc_arab', 'bak_latn',
        'bbc_latn', 'bcl_latn', 'bgp_latn', 'bpy_beng', 'bqc_latn',
        'bsb_latn', 'cak_latn', 'cor_latn', 'crh_cyrl', 'dov_latn',
        'dzo_tibt', 'frr_latn', 'glv_latn', 'hne_deva',
        'inh_cyrl', 'iso_latn', 'kas_deva', 'kat_latn', 'kik_latn',
        'kjh_cyrl', 'kpv_cyrl', 'lez_cyrl', 'lfn_latn', 'lub_latn',
        'mad_latn', 'mag_deva', 'mal_latn',
        'mam_latn', 'mdf_cyrl', 'meo_latn', 'mgh_latn', 'mkw_cyrl',
        'mrj_cyrl', 'mwl_latn', 'nap_latn', 'ngu_latn', 'nhe_latn',
        'nnb_latn', 'nzi_latn', 'pck_latn', 'pon_latn', 'quz_latn',
        'rmc_latn', 'rue_cyrl', 'san_latn', 'sat_olck', 'tam_latn',
        'tbz_latn', 'tcy_knda', 'tdx_latn', 'tiv_latn', 'tlh_latn',
        'tzo_latn', 'uig_latn', 'vep_latn', 'vls_latn',
        'xal_cyrl', 'xmf_geor', 'zap_latn']
langs_10mb = ['abk_cyrl', 'ace_latn', 'ady_cyrl', 'afb_arab', 'aka_latn',
        'alt_cyrl', 'arg_latn', 'ava_cyrl', 'aym_latn', 'ayr_latn', 'aze_cyrl',
        'bam_latn', 'ban_latn', 'bar_latn', 'bem_latn',
        'bew_cyrl', 'bew_latn', 'bho_deva', 'bik_latn', 'bjn_latn',
        'bua_cyrl', 'bug_latn', 'bxr_cyrl', 'cfm_latn', 'che_cyrl',
        'chm_cyrl', 'cjk_latn', 'cnh_latn', 'crh_latn',
        'ctd_latn', 'dar_cyrl', 'dik_latn', 'din_latn', 'diq_latn', 'dyu_latn',
        'ekk_latn', 'ewe_latn', 'fij_latn', 'fon_latn', 'ful_latn', 'fur_latn',
        'fuv_latn', 'gaz_latn', 'glk_arab', 'gom_deva', 'gom_latn',
        'grn_latn', 'hif_latn', 'hil_latn', 'hsb_latn', 'iba_latn',
        'ido_latn', 'iku_cans', 'ilo_latn', 'ina_latn', 'kab_latn',
        'kac_latn', 'kbd_cyrl', 'kbp_latn', 'kea_latn', 'kha_latn',
        'kmb_latn', 'kmr_latn', 'knc_latn', 'kom_cyrl', 'kon_latn',
        'krc_cyrl', 'kum_cyrl', 'lbe_cyrl', 'lij_latn',
        'lin_latn', 'ltg_latn', 'lua_latn', 'luo_latn', 'lvs_latn',
        'lzh_hant', 'mai_deva', 'mhr_cyrl', 'min_latn', 'mon_latn',
        'mos_latn', 'myv_cyrl', 'nan_latn', 'nde_latn', 'nds_latn',
        'new_deva', 'nso_latn', 'oss_cyrl', 'otq_latn',
        'pag_latn', 'pam_latn', 'pcm_latn', 'pms_latn',
        'roh_latn', 'run_latn', 'rus_latn', 'sag_latn', 'sco_latn',
        'shn_mymr', 'sme_latn', 'srd_latn', 'srn_latn', 'ssw_latn',
        'syr_syrc', 'szl_latn', 'tel_latn', 'tet_latn',
        'ton_latn', 'tpi_latn', 'tso_latn', 'tum_latn', 'twi_latn',
        'tyv_cyrl', 'udm_cyrl', 'umb_latn', 'ven_latn', 'vol_latn',
        'wol_latn', 'wuu_hani', 'yua_latn', 'yue_hant',
        'zza_latn']
langs_100mb = ['als_latn', 'arz_arab', 'asm_beng', 'ast_latn', 'azb_arab',
        'aze_arab', 'azj_latn', 'bak_cyrl', 'bod_tibt', 'bre_latn',
        'ceb_latn', 'chv_cyrl', 'ckb_arab', 'cos_latn', 'div_thaa',
        'ell_latn', 'fao_latn', 'fry_latn', 'gla_latn', 'gle_latn',
        'grc_grek', 'gsw_latn', 'guj_latn', 'hat_latn', 'haw_latn',
        'hin_latn', 'hmn_latn', 'ibo_latn', 'jav_latn',
        'kaa_latn', 'kal_latn', 'khk_cyrl', 'khm_khmr', 'kin_latn',
        'knc_arab', 'kur_arab', 'kur_latn', 'lao_laoo', 'lim_latn', 'lmo_latn',
        'ltz_latn', 'lug_latn', 'lus_latn', 'mlg_latn', 'mri_latn',
        'mya_mymr', 'nno_latn', 'nya_latn', 'oci_latn',
        'ori_orya', 'orm_latn', 'pap_latn', 'pbt_arab', 'plt_latn',
        'pnb_arab', 'prs_arab', 'que_latn', 'quy_latn', 'sah_cyrl',
        'san_deva', 'scn_latn', 'smo_latn', 'sna_latn', 'snd_arab',
        'sot_latn', 'sun_latn', 'tir_ethi', 'tsn_latn', 'tuk_latn',
        'uig_arab', 'uzb_cyrl', 'uzn_cyrl', 'uzn_latn', 'vec_latn',
        'war_latn', 'wln_latn', 'xho_latn', 'ydd_hebr', 'yid_hebr',
        'yor_latn', 'zho_hant', 'zsm_latn', 'zul_latn']
langs_1000mb = ['afr_latn', 'amh_ethi', 'arb_arab', 'aze_latn', 'bel_cyrl',
        'ben_beng', 'bos_cyrl', 'bos_latn', 'bul_cyrl', 'cat_latn',
        'ces_latn', 'cym_latn', 'dan_latn', 'deu_latn', 'ell_grek',
        'eng_latn', 'epo_latn', 'est_latn', 'eus_latn', 'fas_arab',
        'fil_latn', 'fin_latn', 'fra_latn', 'glg_latn', 'guj_gujr',
        'hau_latn', 'heb_hebr', 'hin_deva', 'hrv_latn',
        'hun_latn', 'hye_armn', 'ind_latn', 'isl_latn', 'ita_latn',
        'jpn_jpan', 'kaa_cyrl', 'kan_knda', 'kat_geor', 'kaz_cyrl',
        'kir_cyrl', 'kor_hang', 'lat_latn', 'lav_latn', 'lit_latn',
        'mal_mlym', 'mar_deva', 'mkd_cyrl', 'mlt_latn', 'mon_cyrl',
        'msa_latn', 'nep_deva', 'nld_latn', 'nob_latn', 'nor_latn',
        'pan_guru', 'pes_arab', 'pol_latn', 'por_latn', 'pus_arab', 'ron_latn',
        'rus_cyrl', 'sin_sinh', 'slk_latn', 'slv_latn', 'som_latn',
        'spa_latn', 'sqi_latn', 'srp_cyrl', 'srp_latn', 'swa_latn',
        'swe_latn', 'tam_taml', 'tat_cyrl', 'tel_telu', 'tgk_cyrl',
        'tgl_latn', 'tha_thai', 'tur_latn', 'ukr_cyrl', 'urd_arab',
        'uzb_latn', 'vie_latn', 'zho_hans']

# Note: We also train a full model for each language except the 1000mb languages
# (because they already have 1gb of data). Dataset sizes are after byte premium
# scaling.
LANG_SETS = {
    '5mb': set(langs_5mb + langs_10mb + langs_100mb + langs_1000mb),
    '10mb': set(langs_10mb + langs_100mb + langs_1000mb),
    '100mb': set(langs_100mb + langs_1000mb),
    '1000mb': set(langs_1000mb)
}
